### ISSUE TITLE
Theme Not Working with WordPress MU with Domain Mapping Active. 

### ISSUE THREAD

**Issue by postjoe** [dimsemenov/Touchfolio#26]
See for example: 

 Uncaught exception 'Exception' with message 'load error: failed to find /home/artratio/public_html/wp-contenthttp://example.com/wp-content/themes/touchfolio/style-touchfolio-default.less' in /home/artratio/public_html/wp-content/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php:1818 Stack trace: #0 /home/artratio/public_html/wp-content/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php(1902): lessc->compileFile('/home/artratio/...') #1 /home/artratio/public_html/wp-content/plugins/wp-less/lib/Compiler.class.php(77): lessc->cachedCompile('/home/artratio/...', true) #2 /home/artratio/public_html/wp-content/plugins/wp-less/lib/Plugin.class.php(196): WPLessCompiler->cacheStylesheet(Object(WPLessStylesheet), false) #3 /home/artratio/public_html/wp-content/plugins/wp-less/lib/Plugin.class.php(229): WPLessPlugin->processStylesheet('style', false) #4 [internal function]: WPLessPlugin->processStylesheets() #5 /home/artratio/public_html/wp-includes/plugin.php(406): call_user_func_array(Array, Array) #6 /home/artratio/ in /home/artratio/public_html/wp-content/plugins/wp-less/lib/vendor/lessphp/lessc.inc.php on line 1818

**Comment by CryssDOTnet** [comment]
I get that error too (resulting in a blank page), but only when accessing the site via SSL.
